title: Modélisation des systèmes biologiques
description: Site web du cours, avec lien vers les resources utiles.
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
